### ISSUE TITLE
Discussion Forum link on Download page still points to old nevercorner site

### ISSUE THREAD

**Issue by camthesaxman** [Neverball/neverball-website#11]
This should be changed to neverforum.com, which is the new forum site for Neverball.

**Comment by tonesfrommars** [comment]
Addressed in https://github.com/Neverball/neverball-website/commit/7b1117dadf50cfac6e4edbed5e3f18661698a883

**Comment by DearFox** [comment]
neverforum.com is no longer available and leads to the domain purchase page.
